### ISSUE TITLE
terms cannot be deleted

### ISSUE THREAD

**Issue by ChristophNeuner** [Cytomine-ULiege/Cytomine-Web-UI#11]
Hello,

I have encountered an issue with terms in cytomine. 
They cannot be deleted. Neither via the web UI nor via the API.
When I try to delete them via the web UI, a message says, that it is successfully deleted, but after a refresh the term reappears and is also still fetchable via the api.
I am logged in as the default admin.

**Comment by bathienle** [comment]
Hello,

I have tried to reproduce the bug and effectively, the term reappears after the deletion in the pims branch only.
It is fixed by commit [837e0fd](https://github.com/Cytomine-ULiege/Cytomine-core/commit/837e0fd6d618e1311f229193e40c03f35f36a8f2) in Cytomine-core
